In [ ]:
import numpy as np
import pandas as pd
from scipy.io import loadmat
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Load the .mat file
data = loadmat(r"C:\Users\Shampa Barman\Music\Matlab_cancer.mat")

# Extract features and labels
X = data['x']
y = data['t']
# Convert to DataFrame for easier manipulation (if needed)
# X = pd.DataFrame(X)
# y = pd.DataFrame(y)

In [ ]:
X

array([[0.46290091, 0.37056537, 0.46155037, ..., 0.58252595, 0.63768441,
        0.52859127],
       [0.40673611, 0.30643103, 0.27898015, ..., 0.4498    , 0.49972172,
        0.45315089],
       [0.30621525, 0.23971475, 0.20660846, ..., 0.34488742, 0.33761557,
        0.41943002],
       ...,
       [0.08009822, 0.23816822, 0.23361855, ..., 0.15979104, 0.13400809,
        0.1597645 ],
       [0.14462108, 0.18637254, 0.17546801, ..., 0.10701832, 0.1389127 ,
        0.29903768],
       [0.10640488, 0.12637318, 0.0999025 , ..., 0.17790702, 0.177601  ,
        0.17012326]])

In [ ]:
y

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=uint8)

In [ ]:
print(X.shape,y.shape)

(100, 216) (2, 216)

In [ ]:
print(type(X))

<class 'numpy.ndarray'>

In [ ]:
df=pd.DataFrame(X)
df

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,0.462901,0.370565,0.461550,0.375149,0.113849,0.233627,0.566678,0.627662,0.381812,0.455935,...,0.518304,0.679998,0.861971,0.891380,0.728070,0.712350,0.442507,0.582526,0.637684,0.528591
1,0.406736,0.306431,0.278980,0.287317,0.108411,0.117294,0.470354,0.523693,0.247376,0.386352,...,0.362863,0.612171,0.716505,0.804140,0.631755,0.577324,0.378966,0.449800,0.499722,0.453151
2,0.306215,0.239715,0.206608,0.241130,0.086275,0.059205,0.377392,0.429015,0.203156,0.284720,...,0.215489,0.502485,0.593316,0.648416,0.551587,0.458963,0.309647,0.344887,0.337616,0.419430
3,0.488105,0.476358,0.744342,0.426810,0.219954,0.284276,0.669022,0.727860,0.543950,0.509489,...,0.587237,0.695925,0.980418,0.931691,0.811608,0.824525,0.579831,0.648084,0.690683,0.608099
4,0.175169,0.175900,0.152133,0.205859,0.050794,0.047048,0.317999,0.318464,0.122031,0.158107,...,0.133816,0.360841,0.480872,0.468973,0.478606,0.327974,0.247915,0.249213,0.226858,0.348519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.102007,0.163589,0.108145,0.129792,0.108191,0.134398,0.182019,0.124871,0.097083,0.155205,...,0.104120,0.126577,0.230165,0.202313,0.147342,0.126562,0.133148,0.124520,0.144252,0.102442
96,1.669069,2.232187,2.142075,1.951741,3.917728,3.067101,0.692836,1.214623,1.396490,1.293816,...,1.839021,0.822627,0.194489,0.544723,0.923899,1.114880,1.785518,0.996573,1.059562,1.750116
97,0.080098,0.238168,0.233619,0.168771,0.246519,0.138255,0.049109,0.076610,0.271379,0.064827,...,0.178631,0.075754,0.019391,0.100852,0.145998,0.132422,0.185799,0.159791,0.134008,0.159765
98,0.144621,0.186373,0.175468,0.136800,0.079653,0.055678,0.314902,0.213265,0.158562,0.079212,...,0.097148,0.162369,0.448877,0.295088,0.220984,0.195418,0.161314,0.107018,0.138913,0.299038
99,0.106405,0.126373,0.099903,0.116469,0.012750,0.123548,0.136918,0.307412,0.078940,0.120925,...,0.084328,0.198927,0.302474,0.353438,0.113650,0.223841,0.178209,0.177907,0.177601,0.170123

In [ ]:
df=pd.DataFrame(y)
df

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

In [ ]:
 #Transpose DataFrame X
X_transposed = X.T
print("\nTransposed DataFrame X:")
print(X_transposed)

Transposed DataFrame X:
[[0.46290091 0.40673611 0.30621525 ... 0.08009822 0.14462108 0.10640488]
 [0.37056537 0.30643103 0.23971475 ... 0.23816822 0.18637254 0.12637318]
 [0.46155037 0.27898015 0.20660846 ... 0.23361855 0.17546801 0.0999025 ]
 ...
 [0.58252595 0.4498     0.34488742 ... 0.15979104 0.10701832 0.17790702]
 [0.63768441 0.49972172 0.33761557 ... 0.13400809 0.1389127  0.177601  ]
 [0.52859127 0.45315089 0.41943002 ... 0.1597645  0.29903768 0.17012326]]

In [ ]:
# Transpose DataFrame y
y_transposed = y.T
print("\nTransposed DataFrame y:")
print(y_transposed)

Transposed DataFrame y:
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]

In [ ]:
print(X_transposed.shape,y_transposed.shape)

(216, 100) (216, 2)

In [ ]:
# Ensure indices match (usually true by default)
assert len(X_transposed) == len(y_transposed), "Length of X and y must match"

In [ ]:
dfy=pd.DataFrame(y_transposed)
dfy

     0  1
0    1  0
1    1  0
2    1  0
3    1  0
4    1  0
..  .. ..
211  0  1
212  0  1
213  0  1
214  0  1
215  0  1

[216 rows x 2 columns]

In [ ]:
# Define a mapping function to convert binary pair to label
def map_binary_to_label(row):
    if row[0] == 0 and row[1] == 1:
        return 'Normal'
    elif row[0] == 1 and row[1] == 0:
        return 'Cancer'
    else:
        return 'Unknown'  # In case there are any other combinations

# Apply the function to each row and create a new column
dfy['N/C'] = dfy.apply(map_binary_to_label, axis=1)

print("\nDataFrame with Target Labels:")
print(dfy[['N/C']])

DataFrame with Target Labels:
        N/C
0    Cancer
1    Cancer
2    Cancer
3    Cancer
4    Cancer
..      ...
211  Normal
212  Normal
213  Normal
214  Normal
215  Normal

[216 rows x 1 columns]

In [ ]:
y=dfy[['N/C']]
y

        N/C
0    Cancer
1    Cancer
2    Cancer
3    Cancer
4    Cancer
..      ...
211  Normal
212  Normal
213  Normal
214  Normal
215  Normal

[216 rows x 1 columns]

In [ ]:
y.value_counts() # label is not skewed

N/C_Normal
False         121
True           95
Name: count, dtype: int64

In [ ]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5) # cancer --> 1 and normal --> 0

     N/C_Normal
170           1
11            0
107           0
177           1
144           1

In [ ]:
y.dtypes

N/C_Normal    int32
dtype: object

     N/C_Normal
183           1
147           1
80            0
45            0
58            0

N/C_Normal    int32
dtype: object

In [ ]:
X=(X_transposed)
X

array([[0.46290091, 0.40673611, 0.30621525, ..., 0.08009822, 0.14462108,
        0.10640488],
       [0.37056537, 0.30643103, 0.23971475, ..., 0.23816822, 0.18637254,
        0.12637318],
       [0.46155037, 0.27898015, 0.20660846, ..., 0.23361855, 0.17546801,
        0.0999025 ],
       ...,
       [0.58252595, 0.4498    , 0.34488742, ..., 0.15979104, 0.10701832,
        0.17790702],
       [0.63768441, 0.49972172, 0.33761557, ..., 0.13400809, 0.1389127 ,
        0.177601  ],
       [0.52859127, 0.45315089, 0.41943002, ..., 0.1597645 , 0.29903768,
        0.17012326]])

In [ ]:
X=pd.DataFrame(X_transposed)
X.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
150,0.599289,0.482335,0.396989,0.702876,0.304241,0.565064,0.723684,0.379430,2.066268,2.401903,...,0.250892,0.200062,0.030813,1.198251,0.065749,0.193455,0.788271,0.100722,0.271118,0.206702
159,0.530682,0.461087,0.369516,0.559975,0.308552,0.466116,0.503401,0.384273,1.781109,2.105188,...,0.016224,0.015783,0.024919,1.821541,0.113514,0.179858,0.663810,0.017385,0.176135,0.231803
22,0.582982,0.525321,0.424064,0.628094,0.330333,0.346046,0.528821,0.209523,1.490518,1.815130,...,0.618003,0.491413,0.163517,0.820039,0.118659,0.155546,1.089815,0.160775,0.145984,0.138592
27,0.381793,0.230879,0.130748,0.509708,0.094454,0.325208,0.461303,0.181154,1.562314,1.840856,...,0.438801,0.310663,0.153057,0.530887,0.149323,0.144372,1.416809,0.180572,0.190383,0.070508
70,0.452141,0.338447,0.251799,0.603645,0.174594,0.462206,0.613532,0.341824,1.638791,1.960121,...,1.352629,1.123992,0.383766,0.845236,0.104525,0.108428,1.787994,0.184485,0.128869,0.247267

In [ ]:
print(X.shape,y.shape)

(216, 100) (216, 1)

In [ ]:
# Combine DataFrames
df = pd.concat([X, y], axis=1)

#print("Combined DataFrame:")
print(df)

            0         1         2         3         4         5         6  \
0    0.462901  0.406736  0.306215  0.488105  0.175169  0.356551  0.439552
1    0.370565  0.306431  0.239715  0.476358  0.175900  0.353762  0.476071
2    0.461550  0.278980  0.206608  0.744342  0.152133  0.247645  0.304292
3    0.375149  0.287317  0.241130  0.426810  0.205859  0.208770  0.283752
4    0.113849  0.108411  0.086275  0.219954  0.050794  0.116163  0.188402
..        ...       ...       ...       ...       ...       ...       ...
211  0.712350  0.577324  0.458963  0.824525  0.327974  0.552057  0.708814
212  0.442507  0.378966  0.309647  0.579831  0.247915  0.423040  0.560928
213  0.582526  0.449800  0.344887  0.648084  0.249213  0.394702  0.497559
214  0.637684  0.499722  0.337616  0.690683  0.226858  0.410199  0.518084
215  0.528591  0.453151  0.419430  0.608099  0.348519  0.540139  0.716755

            7         8         9  ...        91        92        93  \
0    0.246779  1.373469  1.571959  ...  0.403089  0.189221  0.364127
1    0.258894  1.338965  1.677094  ...  0.494679  0.181136  0.446832
2    0.170356  1.047475  1.193578  ...  1.251828  0.377694  0.486562
3    0.152572  1.213785  1.510149  ...  0.673698  0.214058  0.701985
4    0.069726  0.705930  0.815952  ...  1.729508  0.440756  0.310229
..        ...       ...       ...  ...       ...       ...       ...
211  0.377711  1.781259  2.116528  ...  0.240752  0.046546  1.135407
212  0.290542  1.595510  2.011032  ...  0.401487  0.156010  1.024168
213  0.288319  1.442780  1.639578  ...  0.149762  0.063660  0.957963
214  0.274226  1.361744  1.646028  ...  0.276337  0.076374  0.873837
215  0.336874  1.973202  2.257914  ...  0.119804  0.058726  1.153113

           94        95        96        97        98        99  N/C_Normal
0    0.261905  0.102007  1.669069  0.080098  0.144621  0.106405           0
1    0.164218  0.163589  2.232187  0.238168  0.186373  0.126373           0
2    0.088848  0.108145  2.142075  0.233619  0.175468  0.099903           0
3    0.230137  0.129792  1.951741  0.168771  0.136800  0.116469           0
4    0.139552  0.108191  3.917728  0.246519  0.079653  0.012750           0
..        ...       ...       ...       ...       ...       ...         ...
211  0.058739  0.126562  1.114880  0.132422  0.195418  0.223841           1
212  0.066879  0.133148  1.785518  0.185799  0.161314  0.178209           1
213  0.097699  0.124520  0.996573  0.159791  0.107018  0.177907           1
214  0.049355  0.144252  1.059562  0.134008  0.138913  0.177601           1
215  0.067907  0.102442  1.750116  0.159765  0.299038  0.170123           1

[216 rows x 101 columns]

In [ ]:
df.shape

(216, 101)

In [ ]:
# check for nan values
df.isna().sum()

0             0
1             0
2             0
3             0
4             0
             ..
96            0
97            0
98            0
99            0
N/C_Normal    0
Length: 101, dtype: int64

In [ ]:
df.columns

Index([           0,            1,            2,            3,            4,
                  5,            6,            7,            8,            9,
       ...
                 91,           92,           93,           94,           95,
                 96,           97,           98,           99, 'N/C_Normal'],
      dtype='object', length=101)

In [ ]:
X = df.drop('N/C_Normal', axis=1)
y = df['N/C_Normal']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: N/C_Normal, dtype: int32

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [ ]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
117,0.219671,0.174610,0.145977,0.278734,0.105277,0.388147,0.476471,0.275036,1.506891,1.746563,...,0.373210,0.318407,0.144132,1.670281,0.073720,0.128882,1.306535,0.189869,0.148303,0.122348
47,0.335567,0.196353,0.097065,0.413689,0.087901,0.344336,0.457342,0.242717,1.537546,1.645754,...,0.534452,0.391630,0.234312,1.250842,0.108260,0.086975,1.254973,0.188962,0.133162,0.167043
27,0.381793,0.230879,0.130748,0.509708,0.094454,0.325208,0.461303,0.181154,1.562314,1.840856,...,0.438801,0.310663,0.153057,0.530887,0.149323,0.144372,1.416809,0.180572,0.190383,0.070508
59,0.446608,0.428062,0.355256,0.430199,0.241816,0.335200,0.437496,0.236318,1.179894,1.444809,...,0.689632,0.573892,0.201312,0.658324,0.106453,0.093083,0.883419,0.207201,0.184168,0.099087
40,0.503529,0.397826,0.265457,0.607199,0.164204,0.433760,0.586963,0.294950,1.569394,1.817672,...,0.826620,0.655021,0.180735,0.968595,0.095633,0.160629,1.389370,0.171994,0.227377,0.165386

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=100, activation='relu'),
     keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4384 - loss: 0.9216
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8403 - loss: 0.5497
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7965 - loss: 0.4534
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8065 - loss: 0.3939
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8782 - loss: 0.3400
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8780 - loss: 0.3293
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8921 - loss: 0.3051
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8722 - loss: 0.2920
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8816 - loss: 0.2829
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8611 - loss: 0.3098
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9004 - loss: 0.2507
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8914 - loss: 0.2664
Epoch 13/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8770 - loss: 0.3009
Epoch 14/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9090 - loss: 0.2386
Epoch 15/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8869 - loss: 0.2731
Epoch 16/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8889 - loss: 0.2806
Epoch 17/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9009 - loss: 0.2749
Epoch 18/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8932 - loss: 0.2532
Epoch 19/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8976 - loss: 0.2484
Epoch 20/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8848 - loss: 0.2488
Epoch 21/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9143 - loss: 0.2508
Epoch 22/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8937 - loss: 0.2582
Epoch 23/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8954 - loss: 0.2656
Epoch 24/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9088 - loss: 0.2412
Epoch 25/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9059 - loss: 0.2560
Epoch 26/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8914 - loss: 0.2585
Epoch 27/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9292 - loss: 0.1911
Epoch 28/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9089 - loss: 0.2459
Epoch 29/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9237 - loss: 0.2196
Epoch 30/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9025 - loss: 0.2415
Epoch 31/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9116 - loss: 0.2466
Epoch 32/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9070 - loss: 0.2242
Epoch 33/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9222 - loss: 0.2113
Epoch 34/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9084 - loss: 0.2276
Epoch 35/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9134 - loss: 0.2515
Epoch 36/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9068 - loss: 0.2590
Epoch 37/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9249 - loss: 0.2071
Epoch 38/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9323 - loss: 0.2029
Epoch 39/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9273 - loss: 0.2230
Epoch 40/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9237 - loss: 0.2166
Epoch 41/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9196 - loss: 0.1926
Epoch 42/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9276 - loss: 0.2278
Epoch 43/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9203 - loss: 0.2170
Epoch 44/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9077 - loss: 0.2235
Epoch 45/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9318 - loss: 0.1739
Epoch 46/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9479 - loss: 0.1859
Epoch 47/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9174 - loss: 0.2271
Epoch 48/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9331 - loss: 0.1898
Epoch 49/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9392 - loss: 0.1773
Epoch 50/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9250 - loss: 0.2128
Epoch 51/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.9396 - loss: 0.1843
Epoch 52/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8751 - loss: 0.2560
Epoch 53/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8990 - loss: 0.2211
Epoch 54/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9384 - loss: 0.1761
Epoch 55/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 97us/step - accuracy: 0.9459 - loss: 0.1699
Epoch 56/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9487 - loss: 0.1913
Epoch 57/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9206 - loss: 0.2035
Epoch 58/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8966 - loss: 0.2138
Epoch 59/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9391 - loss: 0.1890
Epoch 60/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9369 - loss: 0.1895
Epoch 61/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9373 - loss: 0.1789
Epoch 62/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9343 - loss: 0.1742
Epoch 63/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9281 - loss: 0.1699
Epoch 64/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 278us/step - accuracy: 0.9528 - loss: 0.1598
Epoch 65/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9365 - loss: 0.1956
Epoch 66/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9477 - loss: 0.1502
Epoch 67/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9398 - loss: 0.1860
Epoch 68/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9405 - loss: 0.1828
Epoch 69/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9374 - loss: 0.1520
Epoch 70/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9434 - loss: 0.1428
Epoch 71/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9450 - loss: 0.1806
Epoch 72/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9491 - loss: 0.1468
Epoch 73/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9367 - loss: 0.1638
Epoch 74/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9663 - loss: 0.1260
Epoch 75/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9544 - loss: 0.1450
Epoch 76/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9427 - loss: 0.1660
Epoch 77/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9418 - loss: 0.1659
Epoch 78/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9418 - loss: 0.1519
Epoch 79/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9676 - loss: 0.1363
Epoch 80/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.9312 - loss: 0.1653
Epoch 81/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9461 - loss: 0.1470
Epoch 82/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9395 - loss: 0.1486
Epoch 83/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9610 - loss: 0.1217
Epoch 84/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9601 - loss: 0.1281
Epoch 85/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9431 - loss: 0.1533
Epoch 86/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 178us/step - accuracy: 0.9529 - loss: 0.1382
Epoch 87/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9489 - loss: 0.1374
Epoch 88/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9064 - loss: 0.1765
Epoch 89/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9656 - loss: 0.1226
Epoch 90/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9433 - loss: 0.1468
Epoch 91/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.9309 - loss: 0.1604
Epoch 92/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9569 - loss: 0.1333
Epoch 93/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9327 - loss: 0.1724
Epoch 94/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9442 - loss: 0.1405
Epoch 95/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9509 - loss: 0.1436
Epoch 96/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9540 - loss: 0.1323
Epoch 97/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9509 - loss: 0.1382
Epoch 98/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9420 - loss: 0.1460
Epoch 99/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9539 - loss: 0.1245
Epoch 100/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9469 - loss: 0.1170

In [ ]:
model.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9081 - loss: 0.1282

[0.12380748242139816, 0.9090909361839294]

In [ ]:
y_pred = model.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[1.7941188e-02 4.9497589e-02 3.5581596e-03 3.1483594e-02 6.6637826e-06
 7.8628240e-03 4.7439886e-03 6.5991867e-01 5.0385410e-01 7.5615162e-07]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        30
           1       0.86      0.86      0.86        14

    accuracy                           0.91        44
   macro avg       0.90      0.90      0.90        44
weighted avg       0.91      0.91      0.91        44